baseURL = "isaacreese.com"
languageCode = "en-us"
theme = "archie"
title = "Isaac Reese"

# Code
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
	mode="dark" # color-mode → light,dark or auto
	featherIconsCDN=true
	subtitle = "Motion Graphics + Cinematography"

# Social Tags

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/isaacreese"
